const chalk = require('chalk') || { green: s => s, red: s => s, yellow: s => s, gray: s => s, bold: s => s, cyan: s => s, magenta: s => s, blue: s => s };
let figures;
try {
  figures = require('figures');
} catch {
  figures = { tick: '✓', cross: '✗', arrow: '→' };
}

/**
 * Display session trace report
 */
class Reporter {
  static display(parsed, stats, costBreakdown, toolUsage, anomalies, timeline) {
    console.log('');
    console.log(chalk.bold.cyan('  🔍 Agent Trace Report'));
    console.log(chalk.gray('  ─────────────────────────────────────────────────────'));
    console.log('');

    // Session Overview
    this.section('📊 Session Overview', [
      `Duration: ${this.formatDuration(parsed.duration)}`,
      `Messages: ${stats.totalMessages} (User: ${stats.userMessages}, Assistant: ${stats.assistantMessages})`,
      `Tool Calls: ${stats.totalToolCalls} (${stats.uniqueTools.length} unique tools)`,
      `Errors: ${stats.errors}`,
      `Retries: ${stats.retries}`,
    ]);

    // Cost Analysis
    this.section('💰 Cost Analysis', [
      `Input Tokens: ${costBreakdown.input.tokens.toLocaleString()} ($${costBreakdown.input.cost.toFixed(4)})`,
      `Output Tokens: ${costBreakdown.output.tokens.toLocaleString()} ($${costBreakdown.output.cost.toFixed(4)})`,
      `Total Tokens: ${costBreakdown.total.tokens.toLocaleString()}`,
      `Estimated Cost: $${costBreakdown.total.cost.toFixed(4)}`,
    ]);

    // Tool Health
    if (Object.keys(toolUsage).length > 0) {
      console.log('');
      console.log(chalk.bold('  🔧 Tool Health'));
      console.log(chalk.gray('  ─────────────────────────────────────────────────────'));
      for (const [name, data] of Object.entries(toolUsage)) {
        const successRate = data.successRate;
        const status = successRate >= 90 ? chalk.green('✓') : successRate >= 70 ? chalk.yellow('⚠') : chalk.red('✗');
        const rate = successRate >= 90 ? chalk.green(`${successRate.toFixed(0)}%`) : successRate >= 70 ? chalk.yellow(`${successRate.toFixed(0)}%`) : chalk.red(`${successRate.toFixed(0)}%`);
        console.log(`  ${status} ${name}: ${data.count} calls, ${rate} success, avg ${data.avgDuration.toFixed(0)}ms`);
      }
    }

    // Anomalies
    if (anomalies.length > 0) {
      console.log('');
      console.log(chalk.bold.yellow('  ⚠️  Anomalies Detected'));
      console.log(chalk.gray('  ─────────────────────────────────────────────────────'));
      for (const a of anomalies) {
        console.log(chalk.yellow(`  ${figures.arrow} ${a.message}`));
      }
    }

    // Active Periods
    const periods = this.getActivePeriodsFromTimeline(timeline);
    if (periods.length > 0) {
      console.log('');
      console.log(chalk.bold('  ⏱️  Active Periods'));
      console.log(chalk.gray('  ─────────────────────────────────────────────────────'));
      for (const period of periods.slice(0, 5)) {
        const start = period.start ? period.start.toLocaleTimeString() : '?';
        const end = period.end ? period.end.toLocaleTimeString() : '?';
        const duration = period.start && period.end ? this.formatDuration((period.end - period.start) / 1000) : '?';
        console.log(`  ${start} → ${end} (${duration}, ${period.count} messages)`);
      }
    }

    // Timeline (last 10 messages)
    if (timeline.length > 0) {
      console.log('');
      console.log(chalk.bold('  📝 Recent Timeline'));
      console.log(chalk.gray('  ─────────────────────────────────────────────────────'));
      for (const entry of timeline.slice(-10)) {
        const time = entry.timestamp ? entry.timestamp.toLocaleTimeString() : '?';
        const duration = entry.duration ? chalk.gray(` (${this.formatDuration(entry.duration)})`) : '';
        const role = entry.role === 'user' ? chalk.cyan('You') : entry.role === 'assistant' ? chalk.green('AI') : chalk.yellow('Tool');
        const preview = entry.contentPreview.replace(/\n/g, ' ').substring(0, 60);
        console.log(`  ${time} ${role}${duration}: ${chalk.gray(preview)}`);
      }
    }

    console.log('');
    console.log(chalk.gray('  ─────────────────────────────────────────────────────'));
    console.log(chalk.gray('  Generated by agent-trace | Read-only, local analysis'));
    console.log('');
  }

  static section(title, lines) {
    console.log(chalk.bold(`  ${title}`));
    console.log(chalk.gray('  ─────────────────────────────────────────────────────'));
    for (const line of lines) {
      console.log(`  ${line}`);
    }
    console.log('');
  }

  static formatDuration(seconds) {
    if (!seconds || seconds < 0) return '?';
    if (seconds < 60) return `${seconds.toFixed(0)}s`;
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ${Math.floor(seconds % 60)}s`;
    return `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m`;
  }

  static getActivePeriodsFromTimeline(timeline) {
    if (timeline.length < 2) return [];
    const periods = [];
    let current = { start: timeline[0].timestamp, end: timeline[0].timestamp, count: 1 };

    for (let i = 1; i < timeline.length; i++) {
      const entry = timeline[i];
      if (!entry.timestamp) continue;
      const gap = (entry.timestamp - current.end) / 1000 / 60;

      if (gap > 10) {
        periods.push(current);
        current = { start: entry.timestamp, end: entry.timestamp, count: 1 };
      } else {
        current.end = entry.timestamp;
        current.count++;
      }
    }
    periods.push(current);
    return periods;
  }
}

module.exports = { Reporter };
